---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: text
  name: subtitle
  label: Subtitle
  default: ''
- name: image
  label: Image
  type: file
  hidden: false
  default: ''
- name: type
  label: Type
  type: text
  hidden: true
  default: page
- type: field_group
  name: focus_group
  label: focus_group
  fields:
  - type: text
    name: icon1
    label: icon1
  - type: textarea
    name: text1
    label: text1
pages:
- hugo/content/_index.md
